const EXCEL_FILE='Data para plantilla modelo R6.xlsm';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={fy:'',format:'',status:''}; let activeData='strategic'; let M={};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ' ).trim();
const num=v=>{if(typeof v==='number')return v;let s=String(v??'').replace(/[^0-9.-]/g,'');return Number(s)||0};
const money=v=>'$'+Math.round(v||0).toLocaleString('en-US'); const rd=v=>'RD$'+Math.round(v||0).toLocaleString('en-US');
const fam=f=>{let n=norm(f);if(n.includes('sirena'))return 'Sirena';if(n.includes('hd')||n.includes('xs'))return 'Aprezio HD / XS';if(n.includes('aprezio'))return 'Aprezio';return clean(f)||'Otro'};
const cls=f=>fam(f)==='Sirena'?'sirena':fam(f)==='Aprezio'?'aprezio':'hd';
const uniq=a=>[...new Set(a.filter(Boolean))].sort();
function rows(wb,name){let ws=wb.Sheets[name]; if(!ws)return []; return XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});}
function findHeader(a,required){return a.findIndex(r=>required.every(k=>r.some(c=>norm(c)===norm(k))))}
function objRows(a,idx){let h=a[idx].map(clean);return a.slice(idx+1).filter(r=>r.some(clean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function val(o,key){let nk=norm(key),k=Object.keys(o).find(x=>norm(x)===nk);return k?o[k]:''}
function qtyFrom(r){let s=[val(r,'Proyecto'),val(r,'Centro'),val(r,'Iniciativa')].join(' ');let m=s.match(/\bx\s*(\d+)\b/i)||s.match(/(\d+)\s*tiendas?/i);return m?Number(m[1]):1}
function storeKey(s){return norm(s).replace(/\b(aprezio|sirena|regular|compacta|market|hd|l|m)\b/g,' ').replace(/\bferrecentro\b/g,' ').replace(/\s+/g,' ').trim()}
function matchPlan(project,plan){let k=storeKey(project); if(!k)return null;return plan.find(p=>{let t=storeKey(p.store);return t&&(k.includes(t)||t.includes(k))})||null}
function parseWorkbook(wb){
  const rs=rows(wb,'Resumen estratégico'), hs=findHeader(rs,['Pilar','Estrategia que agrega valor']);
  const strategic=hs>=0?objRows(rs,hs).filter(x=>['expansion','eficiencia','experiencia'].includes(norm(val(x,'Pilar')))).map(x=>({pillar:clean(val(x,'Pilar')),strategy:clean(val(x,'Estrategia que agrega valor')),actions:[val(x,'Acción 1'),val(x,'Acción 2'),val(x,'Acción 3')].map(clean).filter(Boolean),value:clean(val(x,'Valor para el negocio')),metrics:clean(val(x,'Métricas y metas'))})):[];
  let objective=''; for(let i=0;i<rs.length;i++){if(norm(rs[i][0])==='objetivo de negocio'){objective=clean(rs[i][1]);break}}
  const seg=rows(wb,'Seguimiento'), hseg=findHeader(seg,['ID','Pilar','Acción ejecutable']);
  const roadmap=hseg>=0?objRows(seg,hseg).map(x=>({id:clean(val(x,'ID')),pillar:clean(val(x,'Pilar')),action:clean(val(x,'Acción ejecutable')),deliverable:clean(val(x,'Entregable obligatorio')),value:clean(val(x,'Valor para el negocio')),metric:clean(val(x,'Métrica')),target:clean(val(x,'Meta')),owner:clean(val(x,'Responsable')),date:clean(val(x,'Fecha objetivo')),status:clean(val(x,'Estado')),progress:clean(val(x,'Avance'))})).filter(x=>x.id):[];
  const pr=rows(wb,'Plan '), hp=findHeader(pr,['AF','Tipo','Formato','Tienda','Fecha Apertura']);
  const plan=hp>=0?objRows(pr,hp).map(x=>({fy:clean(val(x,'AF')),type:clean(val(x,'Tipo')),format:clean(val(x,'Formato')),store:clean(val(x,'Tienda')),qty:num(val(x,'Cantidad'))||1,status:clean(val(x,'Estado')),start:clean(val(x,'Fecha Inicio')),opening:clean(val(x,'Fecha Apertura')),leader:clean(val(x,'Lider Iniciativa')),planning:clean(val(x,'Encargado de Planificación')),designer:clean(val(x,'Diseñador')),supervisor:clean(val(x,'Supervisor')),mep:clean(val(x,'Coordinador MEP')),permits:clean(val(x,'Coordinador Tramitación Permisos')),costs:clean(val(x,'Analista de Costos')),purchases:clean(val(x,'Encargado de Compras AF'))})).filter(x=>x.store):[];
  const fr=rows(wb,'Fechas'), hf=findHeader(fr,['Formato','Proyecto','Centro','AF apertura']);
  const strategicProjects=hf>=0?objRows(fr,hf).map(x=>{let p=matchPlan(val(x,'Proyecto'),plan);return {format:clean(val(x,'Formato')),initiative:clean(val(x,'Iniciativa')),project:clean(val(x,'Proyecto')),center:clean(val(x,'Centro')),status:clean(val(x,'Estatus Inic')),purchaseFY:clean(val(x,'AF compra')),purchaseMonth:clean(val(x,'Mes compras')),openingFY:clean(val(x,'AF apertura')),openingMonth:clean(val(x,'Mes apertura')),qty:qtyFrom(x),responsible:p||{}}}).filter(x=>x.project):[];
  const dr=rows(wb,'Data'), hd=findHeader(dr,['Formato','Proyecto','Centro','Supranumero','Ppto. Orden Interna [USD]']);
  const budget=hd>=0?objRows(dr,hd).map(x=>({format:clean(val(x,'Formato')),project:clean(val(x,'Proyecto')),center:clean(val(x,'Centro')),status:clean(val(x,'Estatus Inic')),purchaseFY:clean(val(x,'AF compra')),purchaseMonth:clean(val(x,'Mes compras')),openingFY:clean(val(x,'AF apertura')),openingMonth:clean(val(x,'Mes apertura')),group:clean(val(x,'Agrupador')),su:clean(val(x,'SU')),supranumber:clean(val(x,'Supranumero')),partida:clean(val(x,'Partidas')),qty:num(val(x,'Cant.')),usd:num(val(x,'Ppto. Orden Interna [USD]')),dop:num(val(x,'Ppto. Orden Interna [DOP]')),leadtime:clean(val(x,'Lead time')),purchaseStatus:clean(val(x,'Estatus de compra'))})).filter(x=>x.project||x.supranumber):[];
  const remodel=plan.filter(x=>norm(x.type).includes('arrastre'));
  return {objective,strategic,roadmap,plan,strategicProjects,budget,remodel};
}
function filtStrategic(){return M.strategicProjects.filter(x=>(!state.fy||String(x.openingFY||x.purchaseFY)===state.fy)&&(!state.format||fam(x.format)===state.format)&&(!state.status||x.status===state.status))}
function filtBudget(){return M.budget.filter(x=>(!state.fy||String(x.openingFY||x.purchaseFY)===state.fy)&&(!state.format||fam(x.format)===state.format)&&(!state.status||x.status===state.status))}
function kpis(items){return items.map(([a,b])=>`<div class="kpi"><b>${esc(b)}</b><span>${esc(a)}</span></div>`).join('')}
function initFilters(){uniq(M.strategicProjects.map(x=>x.openingFY||x.purchaseFY)).forEach(v=>$('#fy').add(new Option('AF'+v,v)));['Sirena','Aprezio','Aprezio HD / XS'].forEach(v=>$('#format').add(new Option(v,v)));uniq(M.strategicProjects.map(x=>x.status)).forEach(v=>$('#status').add(new Option(v,v)));['fy','format','status'].forEach(id=>$('#'+id).addEventListener('change',e=>{state[id]=e.target.value;render()}));$('#clear').onclick=()=>{Object.keys(state).forEach(k=>state[k]='');$$('.filters select').forEach(x=>x.selectedIndex=0);render()}}
function renderVision(){let a=filtStrategic();$('#objective').textContent=M.objective;$('#visionKpis').innerHTML=kpis([['Tiendas contempladas',a.reduce((s,x)=>s+x.qty,0)],['Proyectos / paquetes',a.length],['Formatos',new Set(a.map(x=>fam(x.format))).size],['Acciones estratégicas',M.roadmap.length],['Pilares',M.strategic.length]]);$('#temple').innerHTML=`<div class="templeRoof">PILARES · COMPRAS ESTRATÉGICAS</div><div class="templeBase">${esc(M.objective)}</div><div class="pillars">${M.strategic.map((p,i)=>`<article class="pillar"><div class="num">0${i+1}</div><h3>${esc(p.pillar)}</h3><h4>ESTRATEGIA</h4><p>${esc(p.strategy)}</p><h4>PLANES DE ACCIÓN</h4><ul>${p.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>MÉTRICAS</h4><p>${esc(p.metrics).replace(/\n/g,'<br>')}</p></article>`).join('')}<article class="pillar value"><div class="num">04</div><h3>VALOR PARA EL NEGOCIO</h3>${M.strategic.map(p=>`<h4>${esc(p.pillar)}</h4><p>${esc(p.value)}</p>`).join('')}</article></div>`;
  let years=['2026','2027','2028'];$('#strategyRoadmap').innerHTML=`<div class="roadHead"><div>Pilar</div>${years.map(y=>`<div>AF${y}</div>`).join('')}</div>`+M.strategic.map(p=>`<div class="roadRow"><div><b>${esc(p.pillar)}</b></div>${years.map(y=>`<div>${M.roadmap.filter(r=>r.pillar===p.pillar&&String(r.date).includes(y)).map(r=>`<div class="roadItem"><b>${esc(r.id)}</b> ${esc(r.action)}<br><small>${esc(r.date)} · ${esc(r.target)}</small></div>`).join('')}</div>`).join('')}</div>`).join('');
  $('#projectCards').innerHTML=a.slice(0,18).map(projectCard).join('')||'<p>No hay proyectos para estos filtros.</p>';
}
function projectCard(x){let r=x.responsible||{};return `<article class="project"><h3>${esc(x.project)}</h3><div class="meta">${esc(x.format)} · ${x.qty} ${x.qty===1?'tienda':'tiendas'} · ${esc(x.status)}</div><div class="people"><span><b>Centro</b><br>${esc(x.center)}</span><span><b>Apertura</b><br>AF${esc(x.openingFY)} · ${esc(x.openingMonth)}</span><span><b>Tipo</b><br>${esc(r.type||'—')}</span><span><b>Líder</b><br>${esc(r.leader||'—')}</span><span><b>Planificación</b><br>${esc(r.planning||'—')}</span><span><b>Diseño</b><br>${esc(r.designer||'—')}</span><span><b>MEP</b><br>${esc(r.mep||'—')}</span><span><b>Permisos</b><br>${esc(r.permits||'—')}</span><span><b>Costos</b><br>${esc(r.costs||'—')}</span><span><b>Compras AF</b><br>${esc(r.purchases||'—')}</span></div></article>`}
function renderExpansion(){let a=filtStrategic(), f={};a.forEach(x=>f[fam(x.format)]=(f[fam(x.format)]||0)+x.qty);$('#expKpis').innerHTML=kpis([['Tiendas estratégicas',a.reduce((s,x)=>s+x.qty,0)],['Sirena',f.Sirena||0],['Aprezio',f.Aprezio||0],['Aprezio HD / XS',f['Aprezio HD / XS']||0],['Paquetes masivos',a.filter(x=>x.qty>1).length]]);let years=uniq(M.strategicProjects.map(x=>x.openingFY)).filter(Boolean);$('#pipeline').innerHTML=years.map(y=>{let ys=a.filter(x=>x.openingFY===y),g={};ys.forEach(x=>(g[fam(x.format)]??=[]).push(x));return `<div class="yearCol"><h3>AF ${String(y).slice(-2)}</h3>${Object.entries(g).map(([f,xs])=>`<div class="pipeBlock ${cls(f)}"><b>${esc(f)} (${xs.reduce((s,x)=>s+x.qty,0)})</b><br>${xs.map(x=>x.qty>1?`${x.qty} tiendas · ${x.openingMonth}`:x.project).join('<br>')}</div>`).join('')}</div>`}).join('');let rem=M.remodel.filter(x=>!state.fy||x.fy===state.fy).filter(x=>!state.format||fam(x.format)===state.format);let ryrs=uniq(M.remodel.map(x=>x.fy));$('#remodel').innerHTML=`<div class="remRow remHead"><div>Tienda</div>${ryrs.map(y=>`<div>AF${y}</div>`).join('')}</div>`+rem.map(x=>`<div class="remRow"><div>${esc(x.store)}</div>${ryrs.map(y=>`<div>${x.fy===y?'<div class="rbar"></div>':''}</div>`).join('')}</div>`).join('');$('#projectTable').innerHTML=table(['Formato','Proyecto','Centro','Estatus','Cantidad','AF apertura','Mes apertura','Líder','Planificación','Compras AF'],a.map(x=>[x.format,x.project,x.center,x.status,x.qty,x.openingFY,x.openingMonth,x.responsible?.leader||'',x.responsible?.planning||'',x.responsible?.purchases||'']))}
function agg(a,key){let o={};a.forEach(x=>o[key(x)]=(o[key(x)]||0)+x.usd);return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function bars(sel,d,limit=12){d=d.slice(0,limit);let mx=Math.max(...d.map(x=>x[1]),1);$(sel).innerHTML=d.map(([n,v])=>`<div class="barRow"><span>${esc(n||'Sin clasificar')}</span><div class="barTrack"><div class="barFill" style="width:${v/mx*100}%"></div></div><b>${money(v)}</b></div>`).join('')}
function renderCapex(){let a=filtBudget();$('#capexKpis').innerHTML=kpis([['CAPEX asignado USD',money(a.reduce((s,x)=>s+x.usd,0))],['CAPEX DOP',rd(a.reduce((s,x)=>s+x.dop,0))],['Proyectos con CAPEX',new Set(a.map(x=>x.project).filter(Boolean)).size],['Agrupadores',new Set(a.map(x=>x.group).filter(Boolean)).size],['Líneas presupuestarias',a.length]]);bars('#capexFormat',agg(a,x=>x.format));bars('#capexGroup',agg(a,x=>x.group),10);let fs=uniq(a.map(x=>x.format)),groups={};a.forEach(x=>{let g=x.group||'Sin agrupador',s=x.supranumber||'Sin supranúmero';groups[g]??={};groups[g][s]??={};groups[g][s][x.format]=(groups[g][s][x.format]||0)+x.usd});let h=`<thead><tr><th>Agrupador</th><th>Supranúmero</th>${fs.map(f=>`<th>${esc(f)}</th>`).join('')}<th>Total</th></tr></thead><tbody>`;Object.entries(groups).forEach(([g,sus])=>{let gt=Object.values(sus).flatMap(o=>Object.values(o)).reduce((a,b)=>a+b,0);h+=`<tr class="groupRow"><td>${esc(g)}</td><td></td>${fs.map(()=>'<td></td>').join('')}<td class="num">${money(gt)}</td></tr>`;Object.entries(sus).forEach(([s,o])=>{let t=Object.values(o).reduce((a,b)=>a+b,0);h+=`<tr><td></td><td>${esc(s)}</td>${fs.map(f=>`<td class="num">${o[f]?money(o[f]):'—'}</td>`).join('')}<td class="num"><b>${money(t)}</b></td></tr>`})});$('#matrix').innerHTML=h+'</tbody>'}
function table(headers,rows){return `<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody>`}
function renderData(){let q=norm($('#search').value);if(activeData==='strategic'){let a=filtStrategic().filter(x=>!q||norm(JSON.stringify(x)).includes(q));$('#dataTable').innerHTML=table(['Formato','Proyecto','Centro','Estatus','Cantidad','AF compra','Mes compra','AF apertura','Mes apertura'],a.map(x=>[x.format,x.project,x.center,x.status,x.qty,x.purchaseFY,x.purchaseMonth,x.openingFY,x.openingMonth]))}else{let a=filtBudget().filter(x=>!q||norm(JSON.stringify(x)).includes(q));$('#dataTable').innerHTML=table(['Formato','Proyecto','Centro','Agrupador','Supranúmero','CAPEX USD','AF apertura','Mes apertura','Lead time'],a.slice(0,1500).map(x=>[x.format,x.project,x.center,x.group,x.supranumber,money(x.usd),x.openingFY,x.openingMonth,x.leadtime]))}}
function render(){renderVision();renderExpansion();renderCapex();renderData()}
function wire(){$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')});$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeData=b.dataset.set;renderData()});$('#search').oninput=renderData;$('#pdfBtn').onclick=exportPDF}
async function exportPDF(){let btn=$('#pdfBtn');btn.disabled=true;btn.textContent='Generando PDF…';document.body.classList.add('pdf-mode');try{if(window.html2pdf){await html2pdf().set({margin:[8,7,8,7],filename:`Compras_Estrategicas_CAF_${new Date().toISOString().slice(0,10)}.pdf`,image:{type:'jpeg',quality:.96},html2canvas:{scale:1.4,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'landscape'},pagebreak:{mode:['css','legacy']}}).from(document.querySelector('main')).save()}else{window.print()}}catch(e){console.error(e);window.print()}finally{document.body.classList.remove('pdf-mode');btn.disabled=false;btn.textContent='↓ Descargar reporte PDF'}}
async function start(){wire();try{if(!window.XLSX)throw new Error('No se pudo cargar el lector de Excel (SheetJS).');let res=await fetch(encodeURI(EXCEL_FILE)+'?v='+Date.now());if(!res.ok)throw new Error(`No se encontró ${EXCEL_FILE} (${res.status}).`);let ab=await res.arrayBuffer(),wb=XLSX.read(ab,{type:'array',cellDates:false});M=parseWorkbook(wb);if(!M.strategicProjects.length)throw new Error('La hoja Fechas no produjo proyectos. Verifica que conserve sus encabezados.');if(!M.budget.length)throw new Error('La hoja Data no produjo líneas CAPEX. Verifica que conserve sus encabezados.');initFilters();render();$('#sourceStatus').textContent=`Excel cargado · ${M.strategicProjects.length} filas estratégicas · ${M.budget.length.toLocaleString()} líneas CAPEX`;$('#loading').classList.add('hidden')}catch(e){console.error(e);$('#loading').innerHTML=`<div class="error"><b>No se pudo cargar el reporte.</b><br>${esc(e.message)}<br><br>Confirma que <b>${esc(EXCEL_FILE)}</b> esté en la misma carpeta que index.html.</div>`}}
start();
